"""empty message

Revision ID: fe58b292fde8
Revises: f98f5d32d7e4
Create Date: 2019-12-14 22:33:50.606046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe58b292fde8'
down_revision = 'f98f5d32d7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name_category')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name_product', sa.String(), nullable=True),
    sa.Column('desc_product', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id_category'], ),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('name_product')
    )
    op.add_column('clients', sa.Column('id_client', sa.Integer(), nullable=False))
    op.drop_column('clients', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('clients', 'id_client')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
